/**
 * examples/03_choose_pattern/choose.c
 *
 * RIFT Is a Flexible Translator — Proof of Concept #3
 * Ordered pattern selection without replacement.
 *
 * What this shows:
 *   The `choose` function implements index-based selection over a sequence of
 *   candidates where each chosen element is removed from the pool before the
 *   next selection. This is the combinatorial primitive that drives RIFT's
 *   macro-alternative resolution.
 *
 * In the RIFT pattern layer:
 *   - `target_sq` is a list of alternative productions for a macro or rule
 *   - `choose_sq` is a sequence of relative indices generated by the
 *     automaton's state trace during parsing
 *   - The output is the ordered list of selected productions
 *
 * This guarantees:
 *   1. Determinism — the same choose_sq always selects the same productions
 *   2. No duplication — each alternative is consumed at most once
 *   3. Residual awareness — remaining alternatives are still accessible
 *
 * Build:
 *   gcc -std=c11 -Wall -o choose choose.c
 *
 * Run:
 *   ./choose
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

/* ── Core algorithm ──────────────────────────────────────────────────────── */

/**
 * choose — select elements from target_sq in order, without replacement.
 *
 * @param choose_sq   Array of relative indices (0-based into remaining pool)
 * @param choose_len  Length of choose_sq
 * @param target_sq   Pool of candidate strings
 * @param target_len  Length of target_sq
 *
 * Algorithm:
 *   For each index `k` in choose_sq:
 *     1. Walk target_sq, counting only un-used elements.
 *     2. When the skip counter reaches `k`, mark that element used and emit it.
 *
 * Complexity: O(choose_len × target_len) — acceptable for the small grammar
 * alternative lists RIFT typically encounters (< 32 candidates per rule).
 */
void
choose(const int *choose_sq, int choose_len,
       const char **target_sq, int target_len)
{
    bool *used = calloc((size_t)target_len, sizeof(bool));
    if (!used) {
        perror("choose: calloc");
        return;
    }

    for (int i = 0; i < choose_len; i++) {
        int index      = choose_sq[i];
        int skip_count = 0;
        int actual     = -1;

        /* Find the index-th un-used element */
        for (int j = 0; j < target_len; j++) {
            if (!used[j]) {
                if (skip_count == index) {
                    actual = j;
                    break;
                }
                skip_count++;
            }
        }

        if (actual != -1) {
            printf("%s ", target_sq[actual]);
            used[actual] = true;
        } else {
            /* Index out of range — pool exhausted or bad sequence */
            printf("<out-of-range:%d> ", index);
        }
    }

    printf("\n");
    free(used);
}

/* ── Annotated trace ─────────────────────────────────────────────────────── */

/**
 * choose_trace — same as choose but prints each selection step.
 * Useful for understanding how RIFT's automaton resolves ambiguity.
 */
void
choose_trace(const int *choose_sq, int choose_len,
             const char **target_sq, int target_len)
{
    bool *used = calloc((size_t)target_len, sizeof(bool));
    if (!used) { perror("choose_trace: calloc"); return; }

    printf("%-8s  %-8s  %-12s  %s\n", "Round", "Index", "Selected", "Pool (remaining)");
    printf("%-8s  %-8s  %-12s  %s\n", "──────", "──────", "──────────", "────────────────");

    for (int i = 0; i < choose_len; i++) {
        int index      = choose_sq[i];
        int skip_count = 0;
        int actual     = -1;

        for (int j = 0; j < target_len; j++) {
            if (!used[j]) {
                if (skip_count == index) { actual = j; break; }
                skip_count++;
            }
        }

        const char *selected = (actual != -1) ? target_sq[actual] : "?";

        /* Print remaining pool before selection */
        char pool[256] = {0};
        int  pos = 0;
        for (int j = 0; j < target_len && pos < 250; j++) {
            if (!used[j]) {
                pos += snprintf(pool + pos, sizeof(pool) - (size_t)pos,
                                "%s ", target_sq[j]);
            }
        }

        printf("%-8d  %-8d  %-12s  [%s]\n", i, index, selected, pool);

        if (actual != -1) used[actual] = true;
    }

    free(used);
}

/* ── Demo ────────────────────────────────────────────────────────────────── */

int
main(void)
{
    printf("RIFT choose() — Ordered Pattern Selection Without Replacement\n");
    printf("═════════════════════════════════════════════════════════════\n\n");

    /* ── Example 1: Basic selection ────────────────────────────────────── */
    {
        int         choose_sq[]  = {0, 1, 1};
        const char *target_sq[]  = {"a", "b", "c", "d"};
        int         clen = (int)(sizeof choose_sq / sizeof *choose_sq);
        int         tlen = (int)(sizeof target_sq / sizeof *target_sq);

        printf("Example 1 — choose_sq={0,1,1}  target={a,b,c,d}\n");
        printf("─────────────────────────────────────────────────\n");
        choose_trace(choose_sq, clen, target_sq, tlen);
        printf("\nResult: ");
        choose(choose_sq, clen, target_sq, tlen);
    }

    printf("\n");

    /* ── Example 2: RIFT-style grammar alternative resolution ──────────── */
    {
        /*
         * Imagine a RIFT pattern rule:
         *   expr := NUMBER | IDENTIFIER | '(' expr ')' | expr OP expr
         *
         * The automaton trace produces choose_sq = {2, 0} meaning:
         *   - First: pick production index 2 from remaining → '(' expr ')'
         *   - Then:  pick production index 0 from remaining → NUMBER
         */
        int         choose_sq[]  = {2, 0};
        const char *target_sq[]  = {"NUMBER", "IDENTIFIER", "'(' expr ')'", "expr OP expr"};
        int         clen = (int)(sizeof choose_sq / sizeof *choose_sq);
        int         tlen = (int)(sizeof target_sq / sizeof *target_sq);

        printf("Example 2 — Grammar alternative resolution\n");
        printf("choose_sq={2,0}  target={NUMBER, IDENTIFIER, '(' expr ')', expr OP expr}\n");
        printf("────────────────────────────────────────────────────────────────────────\n");
        choose_trace(choose_sq, clen, target_sq, tlen);
        printf("\nResolved productions: ");
        choose(choose_sq, clen, target_sq, tlen);
    }

    printf("\n");

    /* ── Example 3: Determinism verification ───────────────────────────── */
    {
        printf("Example 3 — Same choose_sq always produces same output (determinism)\n");
        printf("──────────────────────────────────────────────────────────────────────\n");

        int         choose_sq[]  = {1, 0};
        const char *target_sq[]  = {"emit_c", "emit_js", "emit_py", "emit_go"};
        int         clen = (int)(sizeof choose_sq / sizeof *choose_sq);
        int         tlen = (int)(sizeof target_sq / sizeof *target_sq);

        printf("Run 1: "); choose(choose_sq, clen, target_sq, tlen);
        printf("Run 2: "); choose(choose_sq, clen, target_sq, tlen);
        printf("Run 3: "); choose(choose_sq, clen, target_sq, tlen);
        printf("(All three runs must be identical)\n");
    }

    return 0;
}
