#include "rift/codec.h"
#include <stdio.h>

int rift_emit_c_target(const rift_cir_program_t *program, FILE *out) {
    if (!program || !out) return -1;

    fprintf(out, "/* Generated by RIFT */\n");
    fprintf(out, "#include <stdio.h>\n\n");

    for (int i = 0; i < program->node_count; i++) {
        const rift_cir_node_t *node = &program->nodes[i];
        switch (node->kind) {
            case RIFT_CIR_CALL:
                fprintf(out, "%s(%s);\n", node->name, node->value);
                break;
            case RIFT_CIR_RETURN:
                fprintf(out, "return %s;\n", node->value);
                break;
            default:
                fprintf(out, "/* CIR node: %s */\n", node->name);
                break;
        }
    }

    return 0;
}
